const express = require("express")
const router = express.Router();

const userRoute = require("./user.route")
const authenticationRoute = require("./authentication.route")
const authorizationRoute = require("./authorization.route")
const imageRoute = require("./image.route")
const roleRoute = require("./role.route")
const permissionRoute = require("./permission.route")
const companyRoute = require("./company.route")
const companyDocumentRoute = require("./companyDocument.route")
const categoryRoute = require("./category.route")
const productRoute = require("./product.route")
const batchRoute = require("./batch.route")
const locationRoute = require("./location.route")
const inventoryRoute = require("./inventory.route")
const inventoryHistoryRoute = require("./inventoryHistory.route")
const notificationRoute = require("./notification.route")
const orderRoute = require("./order.route")
const shipmentRoute = require("./shipment.route")
const verifyHashRoute = require("./verifyHash.route")
const sellerCustomRoute = require("./sellerCustom.route")
const receivingRecordsRoute = require("./receivingRecords.route")
const auditLogRoute = require("./auditLog.route")
const traceabilityRoute = require("./traceability.route")

router.use("/user", userRoute)
router.use("/authentication", authenticationRoute)
router.use("/authorization", authorizationRoute)
router.use("/upload", imageRoute)
router.use("/role", roleRoute)
router.use("/permission", permissionRoute)
router.use("/company", companyRoute)
router.use("/license", companyDocumentRoute)
router.use("/category-product", categoryRoute)
router.use("/product", productRoute)
router.use("/batch", batchRoute)
router.use("/location", locationRoute)
router.use("/inventory", inventoryRoute)
router.use("/inventory-history", inventoryHistoryRoute)
router.use("/notification", notificationRoute)
router.use("/order", orderRoute)
router.use("/shipment", shipmentRoute)
router.use("/verify-hash", verifyHashRoute)
router.use("/seller-custom", sellerCustomRoute)
router.use("/receive-record", receivingRecordsRoute)
router.use("/audit-log", auditLogRoute)
router.use("/traceability", traceabilityRoute)

module.exports = router